export const restaurantData = {
  Dosa: {
    restaurants: [
      {
        name: "Venky's Tiffins",
        rating: 4.5,
        reviews: 2340,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 150,
      },
      {
        name: "Ram Ki Bandi",
        rating: 4.3,
        reviews: 1890,
        deliveryTime: "30-40 mins",
        deliveryCost: 40,
        minOrder: 100,
      },
      {
        name: "Chutneys",
        rating: 4.7,
        reviews: 3120,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 120,
      },
      {
        name: "Minerva",
        rating: 4.4,
        reviews: 1560,
        deliveryTime: "35-45 mins",
        deliveryCost: 50,
        minOrder: 200,
      },
    ],
    related: [
      { id: 61, name: "Masala Dosa", price: 120, img: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__1200_0_0_0_auto.jpg" },
      { id: 62, name: "Onion Dosa", price: 130, img: "https://thumbs.dreamstime.com/b/onion-dosa-plain-recipe-finely-chopped-topping-over-which-gives-very-yummy-taste-also-can-be-eaten-195902443.jpg" },
      { id: 63, name: "Paper Dosa", price: 160, img: "https://static.toiimg.com/thumb/53239433.cms?imgsize=247810&width=800&height=800" },
      { id: 64, name: "Rava Dosa", price: 140, img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/rava-dosa-1024x1536.jpg" },
    ],
  },
  Idli: {
    restaurants: [
      {
        name: "Sri Tiffins",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Idli Factory",
        rating: 4.4,
        reviews: 1800,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
      {
        name: "EatWell",
        rating: 4.5,
        reviews: 1950,
        deliveryTime: "30-40 mins",
        deliveryCost: 35,
        minOrder: 150,
      },
      {
        name: "Udupi House",
        rating: 4.3,
        reviews: 1650,
        deliveryTime: "28-38 mins",
        deliveryCost: 32,
        minOrder: 110,
      },
    ],
    related: [
      { id: 65, name: "Plain Idli", price: 60, img: "https://t3.ftcdn.net/jpg/03/62/02/26/360_F_362022640_fZ6UM0JycJlFDdBiR1pYlNddKfdGvYwR.jpg" },
      { id: 66, name: "Sambar Idli", price: 80, img: "https://i0.wp.com/gomathirecipes.com/wp-content/uploads/2022/08/3297.jpg?fit=1200%2C800&ssl=1" },
      { id: 67, name: "Ghee Idli", price: 90, img: "https://taazakitchen.in/wp-content/uploads/2024/09/Ghee-podi-Thatte-Idli.jpg" },
      { id: 68, name: "Rava Idli", price: 85, img: "https://www.funfoodfrolic.com/wp-content/uploads/2020/07/Rava-Idli-Thumbnail.jpg" },
    ],
  },
  Poori: {
    restaurants: [
      {
        name: "Sri Tiffins",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Idli Factory",
        rating: 4.4,
        reviews: 1800,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
      {
        name: "EatWell",
        rating: 4.5,
        reviews: 1950,
        deliveryTime: "30-40 mins",
        deliveryCost: 35,
        minOrder: 150,
      },
      {
        name: "Udupi House",
        rating: 4.3,
        reviews: 1650,
        deliveryTime: "28-38 mins",
        deliveryCost: 32,
        minOrder: 110,
      },
    ],
    related: [
      { id: 69, name: "Plain Poori", price: 70, img: "https://www.vidhyashomecooking.com/wp-content/uploads/2021/04/PooriRecipe.jpg" },
      { id: 70, name: "Masala Poori", price: 90, img: "https://www.awesomecuisine.com/wp-content/uploads/2013/09/Masala-Poori.jpg" },
      
    ],
  },
  Pesarattu: {
    restaurants: [
      {
        name: "Sri Tiffins",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Idli Factory",
        rating: 4.4,
        reviews: 1800,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
      
      {
        name: "Udupi House",
        rating: 4.3,
        reviews: 1650,
        deliveryTime: "28-38 mins",
        deliveryCost: 32,
        minOrder: 110,
      },
    ],
    related: [
      { id: 73, name: "Plain Pesarattu", price: 60, img: "https://i.ytimg.com/vi/c0PQz7TF7RQ/maxresdefault.jpg" },
      { id: 74, name: "Onion Pesarattu", price: 70, img: "https://i0.wp.com/cookingfromheart.com/wp-content/uploads/2023/01/Pesrattu-Recipe.jpg?w=1200&ssl=1" },
      { id: 75, name: "Cheese Pesarattu", price: 90, img: "https://www.awesomecuisine.com/wp-content/uploads/2008/08/pesarattu.jpg" },
      
    ],
  },
  Biryani: {
    restaurants: [
      {
        name: "Biryani House",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Spice Villa",
        rating: 4.4,
        reviews: 1800,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
      
      {
        name: "Biryani Express",
        rating: 4.3,
        reviews: 1650,
        deliveryTime: "28-38 mins",
        deliveryCost: 32,
        minOrder: 110,
      },
    ],
    related: [
      { id: 77, name: "Dhum Biryani", price: 160, img: "https://tse4.mm.bing.net/th/id/OIP.hAjk5iC-86BzwttZ8h0T-gHaHa?rs=1&pid=ImgDetMain&o=7&rm=3" },
      { id: 78, name: "frypiece biryani", price: 150, img: "https://thumbs.dreamstime.com/b/chicken-fry-piece-biryani-hot-spicy-tender-layered-unique-flavored-dum-cooked-195564567.jpg" },
      { id: 79, name: "Mutton Biryani", price: 170, img: "https://paattiskitchen.com/wp-content/uploads/2023/03/kmc_20230323_230743.jpg" },
      { id: 80, name: "Chicken Boneless Biryani", price: 175, img: "https://tse3.mm.bing.net/th/id/OIP.0t5n8uDzFUSN68nhyhiBQwHaGB?rs=1&pid=ImgDetMain&o=7&rm=3" },
    ],
  },
  Omelette: {
    restaurants: [
      {
        name: "Sri Tiffins",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-30 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Idli Factory",
        rating: 4.4,
        reviews: 1800,
        deliveryTime: "25-35 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
     
    ],
    related: [
      { id: 81, name: "Plain Omelette", price: 80, img: "https://media.istockphoto.com/id/173651967/photo/plain-omelette.jpg?s=612x612&w=0&k=20&c=C_jquOMA0LeBSR-iO2NsfB6eELqvWIhBUVvYet81ZCU=" },
      { id: 82, name: "Cheese Omelette", price: 100, img: "https://bakeitwithlove.com/wp-content/uploads/2021/11/cheese-omelet-sq.jpg" },
      { id: 83, name: "Onion Omelette", price: 90, img: "https://i0.wp.com/cooktogether.com/pinpics/uploads/2016/11/cheese-onion-omelette.jpg?fit=1024%2C801&ssl=1" },
      {
        id: 84,
        name: "Veggie Omelette",
        price: 110,
        img: "/foods/omelette.png",
      },
    ],
  },
  Cake: {
    restaurants: [
      {
        name: "CakeZone",
        rating: 4.8,
        reviews: 3400,
        deliveryTime: "15-25 mins",
        deliveryCost: 20,
        minOrder: 200,
      },
      {
        name: "WarmOven",
        rating: 4.6,
        reviews: 2800,
        deliveryTime: "20-30 mins",
        deliveryCost: 30,
        minOrder: 250,
      },
      {
        name: "Sweet Bake",
        rating: 4.5,
        reviews: 2200,
        deliveryTime: "25-35 mins",
        deliveryCost: 35,
        minOrder: 300,
      },
      {
        name: "Bakers Hub",
        rating: 4.4,
        reviews: 1900,
        deliveryTime: "30-40 mins",
        deliveryCost: 40,
        minOrder: 250,
      },
    ],
    related: [
      { id: 85, name: "Chocolate Cake", price: 250, img: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?cs=srgb&dl=pexels-abhinavcoca-291528.jpg&fm=jpg" },
      { id: 86, name: "Red Velvet Cake", price: 290, img: "https://sugargeekshow.com/wp-content/uploads/2020/11/doctored_red_velvet_featured.jpg" },
      { id: 87, name: "Black Forest", price: 230, img: "https://sweetandsavorymeals.com/wp-content/uploads/2020/02/black-forest-cake-recipe-SweetAndSavoryMeals4-1054x1536.jpg" },
      { id: 88, name: "Pineapple Cake", price: 200, img: "https://tse1.mm.bing.net/th/id/OIP.YWNuiCqbV7o7itvtvZ9wcQHaLI?rs=1&pid=ImgDetMain&o=7&rm=3" },
    ],
  },
  "Pure Veg": {
    restaurants: [
      {
        name: "Green Leaf",
        rating: 4.5,
        reviews: 1200,
        deliveryTime: "25-35 mins",
        deliveryCost: 35,
        minOrder: 150,
      },
      {
        name: "Pure Bites",
        rating: 4.4,
        reviews: 980,
        deliveryTime: "30-40 mins",
        deliveryCost: 40,
        minOrder: 200,
      },
      {
        name: "Veg Delight",
        rating: 4.6,
        reviews: 1500,
        deliveryTime: "20-30 mins",
        deliveryCost: 30,
        minOrder: 180,
      },
      {
        name: "Salad Corner",
        rating: 4.3,
        reviews: 890,
        deliveryTime: "25-35 mins",
        deliveryCost: 25,
        minOrder: 120,
      },
    ],
    related: [
      { id: 89, name: "Veg Thali", price: 150, img: "https://img.freepik.com/premium-photo/veg-thali-from-indian-cuisine-food-platter-consists-variety-veggiespaneer-dish-lentils-jeera-riceroti-sweet-dish-curd-onion-etc-selective-focus_726363-844.jpg?w=2000" },
      
      { id: 91, name: "Mixed Veg Curry", price: 120, img: "https://i.pinimg.com/originals/e1/da/d5/e1dad5315972c8a9db86fb01d69c7ecb.jpg" },
      {
        id: 92,
        name: "Vegetable Biryani",
        price: 160,
        img: "https://www.cookwithkushi.com/wp-content/uploads/2015/04/best_vegetable_biryani_recipe.jpg",
      },
    ],
  },
  Juice: {
    restaurants: [
      {
        name: "Fresh Press",
        rating: 4.4,
        reviews: 980,
        deliveryTime: "15-20 mins",
        deliveryCost: 25,
        minOrder: 100,
      },
      {
        name: "Juice Junction",
        rating: 4.5,
        reviews: 1100,
        deliveryTime: "20-25 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
     
    ],
    related: [
      { id: 93, name: "Orange Juice", price: 60, img: "https://media.istockphoto.com/photos/orange-juice-picture-id154902327?b=1&k=20&m=154902327&s=170667a&w=0&h=AvbzSaxmxhcLXfPhZ6LuCkmj2a2KuSYRflHhOJqad8s=" },
      {
        id: 94,
        name: "Pineapple Juice",
        price: 70,
        img: "https://img.freepik.com/premium-photo/pineapple-juice-with-splashes-with-pineapple-fruit-isolated-white-background-studio-shot_741910-7870.jpg?w=2000",
      },
      { id: 95, name: "Mixed Fruit Juice", price: 80, img: "https://itsallgreektome.london/wp-content/uploads/2019/02/Mixed-Frutis.jpg" },
      { id: 96, name: "Apple Juice", price: 75, img: "https://static.vecteezy.com/system/resources/previews/030/623/981/large_2x/apple-juice-image-hd-free-photo.jpg" },
    ],
  },
  Parotta: {
    restaurants: [
      {
        name: "Kallu's Parotta",
        rating: 4.6,
        reviews: 2100,
        deliveryTime: "20-25 mins",
        deliveryCost: 30,
        minOrder: 120,
      },
      {
        name: "Parotta Plaza",
        rating: 4.4,
        reviews: 1700,
        deliveryTime: "25-30 mins",
        deliveryCost: 35,
        minOrder: 150,
      },
      {
        name: "Kerala Kitchen",
        rating: 4.5,
        reviews: 1900,
        deliveryTime: "22-28 mins",
        deliveryCost: 32,
        minOrder: 140,
      },
      {
        name: "Spice House",
        rating: 4.3,
        reviews: 1500,
        deliveryTime: "28-35 mins",
        deliveryCost: 40,
        minOrder: 160,
      },
    ],
    related: [
      { id: 97, name: "Plain Parotta", price: 40, img: "https://thumbs.dreamstime.com/b/kerala-parotta-popularly-known-as-paratha-porotta-kerala-parotta-popularly-known-as-paratha-porotta-delicacy-193290644.jpg" },
      { id: 98, name: "Egg Parotta", price: 60, img: "https://myfoodstory.com/wp-content/uploads/2025/02/Kerala-Egg-Roast-4.jpg" },
      { id: 99, name: "Chicken Parotta", price: 120, img: "https://media-cdn.tripadvisor.com/media/photo-m/1280/1b/cf/74/4d/parotta-with-pepper-chicken.jpg" },
      { id: 100, name: "Keema Parotta", price: 140, img: "https://www.licious.in/blog/wp-content/uploads/2022/04/Keema-Paratha_24241-min-1-scaled.jpg" },
    ],
  },
  Tea: {
    restaurants: [
      {
        name: "CakeZone",
        rating: 4.8,
        reviews: 3400,
        deliveryTime: "15-25 mins",
        deliveryCost: 20,
        minOrder: 200,
      },
      {
        name: "WarmOven",
        rating: 4.6,
        reviews: 2800,
        deliveryTime: "20-30 mins",
        deliveryCost: 30,
        minOrder: 250,
      },
     
    ],
    related: [
      { id: 101, name: "Black Tea", price: 40, img: "https://tse1.mm.bing.net/th/id/OIP.TR2dqRWtnf9IAsRI7LOASwHaE8?rs=1&pid=ImgDetMain&o=7&rm=3" },
      { id: 102, name: "Green Tea", price: 50, img: "https://static.vecteezy.com/system/resources/thumbnails/025/520/530/small_2x/green-tea-cup-generative-ai-photo.jpg" },
     
      { id: 104, name: "Ginger Tea", price: 55, img: "https://tse4.mm.bing.net/th/id/OIP.qs3Yuwi_Dc1PLfgE12LvyAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3" },
    ],
  },
};

export const allRestaurants = [
  {
    name: "Venky's Tiffins",
    rating: 4.5,
    reviews: 2340,
    deliveryTime: "25-35 mins",
    deliveryCost: 30,
    minOrder: 150,
    cuisine: "South Indian",
    image: "/foods/dosa.png",
  },
  {
    name: "Ram Ki Bandi",
    rating: 4.3,
    reviews: 1890,
    deliveryTime: "30-40 mins",
    deliveryCost: 40,
    minOrder: 100,
    cuisine: "South Indian",
    image: "/foods/dosa.png",
  },
  {
    name: "Chutneys",
    rating: 4.7,
    reviews: 3120,
    deliveryTime: "20-30 mins",
    deliveryCost: 25,
    minOrder: 120,
    cuisine: "South Indian",
    image: "/foods/idli.png",
  },
  {
    name: "Minerva",
    rating: 4.4,
    reviews: 1560,
    deliveryTime: "35-45 mins",
    deliveryCost: 50,
    minOrder: 200,
    cuisine: "South Indian",
    image: "/foods/dosa.png",
  },
  {
    name: "CakeZone",
    rating: 4.8,
    reviews: 3400,
    deliveryTime: "15-25 mins",
    deliveryCost: 20,
    minOrder: 200,
    cuisine: "Bakery",
    image: "/foods/cake.avif",
  },
  {
    name: "WarmOven",
    rating: 4.6,
    reviews: 2800,
    deliveryTime: "20-30 mins",
    deliveryCost: 30,
    minOrder: 250,
    cuisine: "Bakery",
    image: "/foods/cake.avif",
  },
  {
    name: "Green Leaf",
    rating: 4.5,
    reviews: 1200,
    deliveryTime: "25-35 mins",
    deliveryCost: 35,
    minOrder: 150,
    cuisine: "Pure Veg",
    image: "/foods/pureveg.png",
  },
  {
    name: "Fresh Press",
    rating: 4.4,
    reviews: 980,
    deliveryTime: "15-20 mins",
    deliveryCost: 25,
    minOrder: 100,
    cuisine: "Beverages",
    image: "/foods/juice.jpg",
  },
  {
    name: "Kallu's Parotta",
    rating: 4.6,
    reviews: 2100,
    deliveryTime: "20-25 mins",
    deliveryCost: 30,
    minOrder: 120,
    cuisine: "Kerala",
    image: "/foods/parotta.png",
  },
  {
    name: "Spice House",
    rating: 4.5,
    reviews: 1650,
    deliveryTime: "30-40 mins",
    deliveryCost: 40,
    minOrder: 200,
    cuisine: "North Indian",
    image: "/foods/dosa.png",
  },
];
